---
- name: Install FrontKeeper
  pip: requirements='https://raw.githubusercontent.com/kpichardie/front-keeper/master/requirements.txt' 

- name: Clone FrontKeeper
  git: repo=https://github.com/kpichardie/front-keeper.git
       dest=/var/www/front-keeper

- name: Copy Frontkeeper configuration
  template: src=settings.py.j2 dest={{frontkeeper_clone_path}}/front-keeper/frontkeeper/frontkeeper/settings.py

- file: path={{passkeeper_path}} owner={{django_user}} group=root mode=0755 state=directory

