---
- include: package.yml
- include: nginx.yml
  when: manage_nginx 

- name: Install FrontKeeper
  pip: requirements='https://raw.githubusercontent.com/kpichardie/front-keeper/master/requirements.txt' 

- name: Clone FrontKeeper
  git: repo=https://github.com/kpichardie/front-keeper.git
       dest=/var/www/front-keeper

- name: Copy supervisor configuration
  template: src=supervisor-frontkeeper.conf.j2 dest=/etc/supervisor/conf.d/frontkeeper.conf
  notify: restart supervisor

- file: path={{passkeeper_path}} owner={{django_user}} group=root mode=0755 state=directory

- service: name=supervisor state=started

